# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: products.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'products.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproducts.proto\"A\n\x06pimage\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\t\x12\r\n\x05price\x18\x03 \x01(\t\x12\x0b\n\x03sex\x18\x04 \x01(\t\"0\n\x05\x41ssin\x12\x18\n\x07pimages\x18\x01 \x03(\x0b\x32\x07.pimage\x12\r\n\x05\x63over\x18\x02 \x03(\t\"$\n\nPicPayload\x12\x16\n\x06\x61ssets\x18\x01 \x01(\x0b\x32\x06.Assinb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'products_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PIMAGE']._serialized_start=18
  _globals['_PIMAGE']._serialized_end=83
  _globals['_ASSIN']._serialized_start=85
  _globals['_ASSIN']._serialized_end=133
  _globals['_PICPAYLOAD']._serialized_start=135
  _globals['_PICPAYLOAD']._serialized_end=171
# @@protoc_insertion_point(module_scope)
